/*
 * This class creates the card value, generated by a random number. 
 */
public class Card {
	private int rand; 
	public int value;
	//Card constructor assigns randomly determined values to the card
	public Card() {
		rand = (int)(Math.random() * 52) + 1;
        if(rand >= 0 && rand <= 3) {
        	value = 2;      	 	
        } else if(rand >= 4 && rand <= 7) {
        	value = 3;      	 	
        } else if(rand >= 8 && rand <= 11) {
        	value = 4;      	 	
        } else if(rand >= 12 && rand <= 15) {
        	value = 5;      	 	
        } else if(rand >= 16 && rand <= 19) {
        	value = 6;      	 	
        } else if(rand >= 20 && rand <= 23) {
        	value = 7;      	 	
        } else if(rand >= 24 && rand <= 27) {
        	value = 8;      	 	
        } else if(rand >= 28 && rand <= 31) {
        	value = 9;      	 	
        } else if(rand >= 32 && rand <= 47) {
        	value = 10;      	 	
        } else {
        	value = 11;      	 	
        } 
	}
	//Returns card value
	public int getValue() {
		return value;
	}
}